In [42]:
import numpy as np
import pandas as pd

In [43]:
df = pd.read_csv("/workspaces/baseline/exp/data_for_plot_creation/wandb_IoUs_TEST_SET_all_classes.csv")

In [44]:
df

epoch  weight: online paste p=0.8 - _step  \
0      1                                  95   
1      2                                 196   
2      3                                 297   
3      4                                 398   
4      5                                 499   
5      6                                 600   

   weight: online paste p=0.8 - _step__MIN  \
0                                       91   
1                                      192   
2                                      293   
3                                      394   
4                                      495   
5                                      596   

   weight: online paste p=0.8 - _step__MAX  \
0                                       99   
1                                      200   
2                                      301   
3                                      402   
4                                      503   
5                                      604   

   weight: online paste p=0.8 - per_class/iou/total/background  \
0                                           0.970190             
1                                           0.970267             
2                                           0.970319             
3                                           0.970311             
4                                           0.970370             
5                                           0.970348             

   weight: online paste p=0.8 - per_class/iou/total/background__MIN  \
0                                           0.970190                  
1                                           0.970267                  
2                                           0.970319                  
3                                           0.970311                  
4                                           0.970370                  
5                                           0.970348                  

   weight: online paste p=0.8 - per_class/iou/total/background__MAX  \
0                                           0.970190                  
1                                           0.970267                  
2                                           0.970319                  
3                                           0.970311                  
4                                           0.970370                  
5                                           0.970348                  

   weight: online paste p=0.8 - per_class/iou/total/buffer_stop  \
0                                           0.008149              
1                                           0.008147              
2                                           0.008096              
3                                           0.008105              
4                                           0.008108              
5                                           0.008112              

   weight: online paste p=0.8 - per_class/iou/total/buffer_stop__MIN  \
0                                           0.008149                   
1                                           0.008147                   
2                                           0.008096                   
3                                           0.008105                   
4                                           0.008108                   
5                                           0.008112                   

   weight: online paste p=0.8 - per_class/iou/total/buffer_stop__MAX  ...  \
0                                           0.008149                  ...   
1                                           0.008147                  ...   
2                                           0.008096                  ...   
3                                           0.008105                  ...   
4                                           0.008108                  ...   
5                                           0.008112                  ...   

   weight: online sparse p=0.9, r=40-50 - per_

In [45]:
df.columns = df.columns.str.replace("weight: online paste p=0.0 -", "baseline", regex=True)
df.columns = df.columns.str.replace("weight: online sparse p=0.9, r=40-50 -", "best_sparse",regex=True)
df.columns = df.columns.str.replace("weight: online paste p=0.8 -",  "best_paste",regex=True)
df.columns = df.columns.str.replace("per_class/iou/total/", "", regex=True)
df = df.drop(columns=[col for col in df.columns if 'MIN' in col or 'MAX' in col]) # Remove the useless columns that wandb generates
df.columns = df.columns.str.replace("/track", "m", regex=True)



In [46]:
df

epoch  best_paste _step  best_paste background  best_paste buffer_stop  \
0      1                95               0.970190                0.008149   
1      2               196               0.970267                0.008147   
2      3               297               0.970319                0.008096   
3      4               398               0.970311                0.008105   
4      5               499               0.970370                0.008108   
5      6               600               0.970348                0.008112   

   best_paste catenary_pole  best_paste person  best_paste road_vehicle  \
0                  0.758282           0.772082                 0.773313   
1                  0.755728           0.771887                 0.771344   
2                  0.758334           0.772392                 0.769578   
3                  0.758536           0.772316                 0.769809   
4                  0.758434           0.772126                 0.770327   
5                  0.758467           0.771914                 0.769582   

   best_paste signal  best_paste track  best_paste train  ...  \
0           0.522522          0.813415          0.574747  ...   
1           0.518729          0.813282          0.578135  ...   
2           0.520429          0.813264          0.579022  ...   
3           0.521618          0.813382          0.578018  ...   
4           0.521706          0.813511          0.579666  ...   
5           0.522326          0.813426          0.579448  ...   

   best_sparse _step  best_sparse background  best_sparse buffer_stop  \
0                 95                0.970286                 0.002877   
1                196                0.970191                 0.002871   
2                297                0.970197                 0.003440   
3                398                0.970219                 0.003584   
4                499                0.970228                 0.003445   
5                600                0.970269                 0.003539   

   best_sparse catenary_pole  best_sparse person  best_sparse road_vehicle  \
0                   0.756683            0.772672                  0.735126   
1                   0.753715            0.773496                  0.735763   
2                   0.754200            0.773071                  0.735812   
3                   0.753884            0.773547                  0.735694   
4                   0.754561            0.773539                  0.735168   
5                   0.754353            0.773592                  0.737157   

   best_sparse signal  best_sparse track  best_sparse train  \
0            0.532715           0.806047           0.573293   
1            0.527806           0.806171           0.571680   
2            0.528615           0.806136           0.571420   
3            0.528600           0.806205           0.572193   
4            0.530187           0.806180           0.572546   
5            0.530749           0.806244           0.574020   

   best_sparse val/total/mIoU  
0                    0.643712  
1                    0.642712  
2                    0.642861  
3                    0.642991  
4                    0.643232  
5                    0.643740  

[6 rows x 31 columns]

In [47]:
df.filter(regex="best_paste").iloc[0,1:].values*100

array([97.01900764,  0.81490105, 75.82824528, 77.2081966 , 77.33128283,
       52.25221804, 81.3414538 , 57.47471368, 64.90875236])

In [48]:
df.filter(regex="baseline").iloc[0,1:].values*100

array([97.08530402,  0.53475936, 71.00931615, 77.98065141, 72.05689631,
       56.83255279, 81.29371327, 59.87370812, 64.58336268])

In [49]:
df.filter(regex="best_sparse").iloc[0,1:].values*100

array([97.02864213,  0.287687  , 75.66825614, 77.26715169, 73.51264923,
       53.27145015, 80.60469321, 57.32927747, 64.37122588])

In [50]:
columns = [
    "background", "buffer_stop", "catenary_pole", "person", 
    "road_vehicle", "signal", "track", "train", "val/total/mIoU"
]
run_values = np.vstack((df.filter(regex="baseline").iloc[0,1:].values*100,
                       df.filter(regex="best_sparse").iloc[0,1:].values*100, 
                       df.filter(regex="best_paste").iloc[0,1:].values*100))
# Create the DataFrame
values_df = pd.DataFrame(run_values, columns=columns)

In [53]:
desired_order = ["background", "person", "train", "road_vehicle", "track", "catenary_pole", "signal", "buffer_stop", "val/total/mIoU"]
values_df=values_df[desired_order]
values_df.round(2)

background  person  train  road_vehicle  track  catenary_pole  signal  \
0       97.09   77.98  59.87         72.06  81.29          71.01   56.83   
1       97.03   77.27  57.33         73.51  80.60          75.67   53.27   
2       97.02   77.21  57.47         77.33  81.34          75.83   52.25   

   buffer_stop  val/total/mIoU  
0         0.53           64.58  
1         0.29           64.37  
2         0.81           64.91